### ISSUE TITLE
TVDB API V3 deprecated 

### ISSUE THREAD

**Issue by IbyFoReal** [mynttt/UpdateTool#117]
Great tool - with TVDB now stating that the API v3 is being deprecated and to use v4 can is there any way to use the v4 API for this tool?

**Comment by mynttt** [comment]
Hello! V4 is already supported since over a year, to use it you need to have a pin that you supply to ``TVDB_API_KEY`` instead of your v3 key.

You can get a pin either by paying a monthly fee or adding some info which rewards you with a key. I don't know the exact terms but search on reddit there's people who've gone that way.
