### ISSUE TITLE
rename project for better visibility

### ISSUE THREAD

**Issue by b2un0** [mynttt/UpdateTool#12]
Hi,

i think `UpdateTool` ist not a really good name where can people find this awesome Plex Tool!

i suggest an name for Github and DockerHub like this:
- `rating-updater-for-plex`
- `rating-fixer-for-plex`

in addition, the description on the DockerHub says nothing about Plex. You should enable Auto Build on DockerHub and Link them to your GitHub Repo, than you have the `readme.md` from here ;)

This tool is the best I've ever found, right after Tautulli.
It has to be found much better by other people

**Comment by mynttt** [comment]
I'm glad you enjoy this tool! I agree the name is truly bland, I had it named Plex Imdb Update Tool first but then back paddled when the reddit post got quite some attention.

The old url still redirects to this repository: https://github.com/mynttt/PlexImdbUpdateTool

I'm afraid that either IMDB or Plex could create some trademark drama should this tool ever get really big.

I mean Tautuli was named PlexPy first and then renamed out of nowhere, the maintainer never said that he was forced but I belive it did happen for a reason. 

The best I can do is to add more keywords and metadata to the readmes and repositories. I would love for more people to discover this tool tho! But I don't know if I'm willing to change the name as these companies do spook me lol

**Comment by b2un0** [comment]
Yes that's true.
You cannot put the name of the protected product in the **first** place.
This is also the reason why many apps have disappeared from smartphone stores, these must always be called `myTool for XY`. Apps like `Whatsapp Emojis` are forbidden, but Apps like `Emojis for Whatsp`p are still allowed!

**Comment by b2un0** [comment]
another idea was `rating-updater-for-pms`, no `plex`, no `imdb` and you could add another sources like `Rotten Tomatoes` (as suggests on Reddit) :D

**Comment by mynttt** [comment]
I did not know that! Another point is that I'm afraid to create confusion by renaming the tool again :/ I guess most people know it as update tool now and dockerhub also does not allow renaming images.

I did however update the docker readme by making it a subset of the github readme and also changed the docker short descriptor to something that mentions Plex and Imdb to make it less confusing and hopefully more searchable!

I looked into autobuild and it seems to not support multi arch that well currently. I'm building the images with the experimental ```dockerx``` right now. Autobuild seems to support multiple Dockerfiles with different tags tho but not building all images under different architectures under a comman tag like the ```dockerx``` does (unless I'm getting something wrong here).

I would love to support Rotten Tomatoes but the problem is that they don't release their ratings like IMDB does and their API seems to be private and only for serious business with licensing only :/

I will however make the tool more useful by looking into IMDB matching for TV Shows as well!
