### ISSUE TITLE
 Unable to set up server: sqlite3_statement_backend::loadOne: database disk image is malformed (N4soci10soci_errorE)

### ISSUE THREAD

**Issue by BeetleJuice4** [mynttt/UpdateTool#124]
I'm running an Unraid server and Plex updated itself a few days ago and ever since I can't access it through the app. The files are all in tack and I see it's still running and even executing trash dumps. But the log shows this error and repeating.

**Comment by mynttt** [comment]
I feel one reason why this happened was maybe that the Plex SQLite binary within the container was too old. I have now updated it to the latest Plex version.

Might be useful to set-up the building of images in an automated way that monitors recent Plex releases for the future.

The problem is that Plex has diverged so much from the standard Sqlite interface by using weird Plug-Ins and other stuff that write access to the database via the standard JDBC driver is no longer safely possible since years.

To bypass this the container embeds the Plex SQLite binary which it then calls from the CLI to perform write updates.

Not the best way; but sadly the only way to even interact with the database anymore. Because Plex API does not allow me to change the fields I have to change I still need to resort to using this path of doing writes.

I'd recommend: 

- backups, backups and backups of the DB
- Try this tool to fix the DB it has a very high success rate: https://github.com/ChuckPa/PlexDBRepair
- Try out the newly released docker image

Let me know how it went
