### ISSUE TITLE
(Request) Age rating

### ISSUE THREAD

**Issue by djnaff** [mynttt/UpdateTool#24]
Please can you update the tool to include age ratings from the tmdb api for movies with no age rating as this is another problem with plex's data.

**Comment by mynttt** [comment]
I just took a look at the API. This is something that I could look into. Sounds like a good idea!

Since this is a locale dependent thing I would have to plan a head and allow some customization options as well. 

Since I am German I would like to only have the german FSK ratings, someone from the US would likely get the MPAA ratings and users of other countries would probably have other age rating providers.

I guess it is possible to obtain this information from the plex library metadata so nobody would have to configure this manually.

Probably would also be a good idea to allow fallback chains and overrides so the users of this feature can customize the tool to their liking if they're unhappy with the default age ratings.

I'm also currently doing my bachelor thesis so Idk when I have time to actually implement this. Probably next week or so.

**Comment by owanneke** [comment]
you could determine location based on a geolocation of the external IP address if the country is not defined.

**Comment by mynttt** [comment]
I will close this for now as there is inactivity and it does not seem to be an issue anymore. The new plex movie agent should've fixed this. If not you can comment here to reopen the issue.
