### ISSUE TITLE
Java heap space crash

### ISSUE THREAD

**Issue by weirdcrap** [mynttt/UpdateTool#25]
Hey, love the tool it has been great for keeping my IMDB stuff up to date.

I requested an API key from TheTVDB just to play with your tool some more and once I added TVDB support it crashes with Java heap space errors every time it runs.

I'm running in a docker on UnRAID.

I didn't see any closed issues for this, sorry if this has been covered before.

[updatetool.log](https://github.com/mynttt/UpdateTool/files/4663396/updatetool.log)

**Comment by mynttt** [comment]
Hi!

Thanks for bringing this up. I looked through the log. Interesting that there are tons of 405 errors regarding the TVDB API. I just checked one of those failed API calls and it worked on my side.

I guess it might have to do with the TVDB API itself. I hope those go away otherwise I would have to investigate that.

The crash seems to be memory related. Your TV Show library seems to have nearly 40000 items. I guess the memory hard limit of 256MB is not enough to handle such a large library. I will update the docker file tomorrow to allow setting the memory limit manually via an environment variable.

Once that is done I'll notify you in this issue and you can then try it with 512MB or if actually necessary 1024MB. At 40000 items there are tons of Strings loaded that can easily eat up a good portion of the available RAM.

**Comment by weirdcrap** [comment]
Haha yeah my TV show library is a bit large

![image](https://user-images.githubusercontent.com/22824785/82601631-784ccf00-9b75-11ea-828b-0a22f7a8020f.png)

I assumed the 405 errors were due to rate limiting as it seems to hit the API as fast as humanly possible, I did not try the API calls outside of the tool though.

A configurable variable would be nice for Java's memory, I already limit my RAM for my dockers using the docker "--Memory=2GB" parameter.

**Comment by mynttt** [comment]
Alright I have updated the Dockerfile.

You can specify a custom max. heap via the environment variable `JVM_MAX_HEAP`. Maybe you try out `512m` first and if it still crashes try `1g`. Let me know if the error still persists!

I also changed the tool to request garbage collection after every run and tweaked the JVM startup settings so unused allocated heap space is released back to the OS at a certain threshold. So if a run requires 512MB the garbage collection will push it down to something like 12-20MB after the task has finished and the JVM will shrink to something like 20-40MB. So unused heap is not stolen from the OS anymore.

The 405 errors usually come in place when you request a resource with the wrong method i.e. `GET` where `POST` is required. I have no idea why TVDB would return that since `GET` is used on a `GET` resource. APIs are weird, their website does not mention that code in the documentation for that endpoint. No idea whats happening there tbh.

**Comment by weirdcrap** [comment]
Thanks for the update! 

I set the variable to start at 512m and restarted the container. It does not appear to immediately execute a ratings sync anymore? Does it now only run when scheduled even at container start?

When I first started playing with the container every time it was restarted a sync would start. I can wait for the next scheduled, just wasn't sure if this was an issue on my end or a change in behavior.

**Comment by mynttt** [comment]
It should start immediately. I changed the backend so the logs will look differently now at startup. Can you upload the log to this issue?

**Comment by weirdcrap** [comment]
Sure, this is literally all that's been logged since I started the container about four hours ago:

`[INFO ] - 2020-05-23 13:58:11 @ Main.loadImplementation: Loaded implementation << imdb-docker << updatetool.imdb.ImdbDockerImplementation
[INFO ] - 2020-05-23 13:58:11 @ Main.main: Running version: 1.3.9
[INFO ] - 2020-05-23 13:58:11 @ Main.main: Args: {imdb-docker={schedule=24}}
[INFO ] - 2020-05-23 13:58:11 @ Main.main: << INIT: imdb-docker @ {schedule=24} >>
[INFO ] - 2020-05-23 13:58:11 @ ImdbDockerImplementation.bootstrap: No TMDB API key detected. Will not process TMDB backed Movie and TV Series libraries and TMDB orphans.
[INFO ] - 2020-05-23 13:58:11 @ Main.testApiTvdb: Testing TVDB API authorization: apikey=*SNIP*
[INFO ] - 2020-05-23 13:58:12 @ Main.testApiTvdb: Test passed. API Key is valid.
[INFO ] - 2020-05-23 13:58:12 @ ImdbDockerImplementation.bootstrap: TVDB API authorization enabled IMDB rating update for TV Series with the TVDB agent.
[INFO ] - 2020-05-23 13:58:12 @ ImdbDockerImplementation.bootstrap: Starting IMDB Watchdog
[INFO ] - 2020-05-23 13:58:12 @ ImdbDockerImplementation.bootstrap: Plex data dir: /plexdata
[INFO ] - 2020-05-23 13:58:12 @ ImdbDockerImplementation.bootstrap: Capabilities: [TVDB]
[INFO ] - 2020-05-23 13:58:12 @ Main.main: << INIT SUCCESS >>
[INFO ] - 2020-05-23 13:58:12 @ Scheduler.go: Scheduler is loading tasks... Blocking until completely set-up and ready to go.
[INFO ] - 2020-05-23 13:58:12 @ Scheduler.go: Scheduling tasks...
[INFO ] - 2020-05-23 13:58:12 @ Scheduler.lambda$go$0: Scheduled imdb-docker task to run @ every 24 hour(s).
[INFO ] - 2020-05-23 13:58:12 @ Scheduler.lambda$go$1: Queued task imdb-docker for immediate execution.
[INFO ] - 2020-05-23 13:58:12 @ Scheduler.go: Unblocking scheduler...
[INFO ] - 2020-05-23 13:58:12 @ Scheduler.go: Running supplied tasks immediately NOW!
`

**Comment by mynttt** [comment]
Whatever happened there should not happen now anymore. Let me know if it persists.

**Comment by weirdcrap** [comment]
It seems to be working now! The process didn't get to finish because Comcast is crap, but that is an all to familiar story for most of us. Thanks for your help.
