### ISSUE TITLE
IMDB ID: XXX supplies no valid rating := 'null'

### ISSUE THREAD

**Issue by mrjohnpoz** [mynttt/UpdateTool#30]
So running 1.3.9b in docker on synology ds918+ and has been working perfectly.. This prob the best tool that has ever been written for plex btw.

While a few things in my library, do not have entries in imdb, or the rating is blank, so understand those... But recently added brave new world 2020.. Which clearly has rating.. And even eps have ratings... But seeing these errors in the log.

https://www.imdb.com/title/tt9814116/
I currently show rating of 6.7 with 238 votes but updatetool is logging this.
[WARN ] - 2020-07-16 16:49:11 @ ImdbTransformer.needsNoUpdate: Ignoring: 'Brave New World (2020)' with IMDB ID: tt9814116 supplies no valid rating := 'null'

With eps showing the same
example
https://www.imdb.com/title/tt10851650/
'Want and Consequence' with IMDB ID: tt10851650 supplies no valid rating := 'null'

But if you look via just web browser those TTs all have ratings.. So confused.

Is there some sort of min number of votes for them to be valid?  
Is there anyway to update the logging level to see exactly what is being returned, so maybe figure out why this isn't working for this 1 show.. I have hundreds of other shows and movies, and all working fantastic... I had no idea that ratings can fluctuate so much until started running this tool and looking at the log every few days.

Any more info that I can provide - just ask.

**Comment by mynttt** [comment]
Im glad you enjoy the tool! 

The issue run into is regarding the dataset which is downloaded from https://datasets.imdbws.com/. 
For UpdateTool it expires after 1 day. After that it is downloaded again. In the logs it will look like this:

```bash
root@5c12ce3b0de2:/config# cat updatetool.0.log | grep violates
[INFO ] - 2020-05-26 15:36:38 @ ImdbRatingDatasetFactory.requestSet: IMDB Dataset has the timestamp: 1590402532193 and violates the update every 86400000 ms constraint. Refreshing dataset...
[INFO ] - 2020-05-27 16:36:38 @ ImdbRatingDatasetFactory.requestSet: IMDB Dataset has the timestamp: 1590500200876 and violates the update every 86400000 ms constraint. Refreshing dataset...
[INFO ] - 2020-05-29 04:36:38 @ ImdbRatingDatasetFactory.requestSet: IMDB Dataset has the timestamp: 1590590199958 and violates the update every 86400000 ms constraint. Refreshing dataset...
[INFO ] - 2020-05-30 16:36:38 @ ImdbRatingDatasetFactory.requestSet: IMDB Dataset has the timestamp: 1590719800879 and violates the update every 86400000 ms constraint. Refreshing dataset...
[INFO ] - 2020-06-01 04:36:38 @ ImdbRatingDatasetFactory.requestSet: IMDB Dataset has the timestamp: 1590849399925 and violates the update every 86400000 ms constraint. Refreshing dataset...
...
```

When an IMDB ID is resolved, it is queried via this set. If for some reason the ID is not mapped by the dataset, 'null' will be returned to indicate that there is no value associated with the ID. This usually happens when the local dataset is not up to date or IMDB has not yet refreshed their dataset.

I believe that IMDB is sometimes slow to refresh their datasets and it can take a few days until ratings, that are visible on their website are reflected through the dataset.

tt9814116 already seems to be mapped by the current dataset while tt10851650 is still missing. My guess is that in a few days the rating should be updated for these items.

Otherwise, there is always the possibility to add some web scraping capabilities to UpdateTool to deal with stuff like this. But currently I don't have time for that as I'm at the end of writing my bachelor thesis. If the issue persits I might be able to look into it in a month or so.

**Comment by mrjohnpoz** [comment]
Thank you for such a detailed response.. So just give it a few days and should be good ;)

And yes love this tool!!  Its way better than any sliced bread have ever had...  It really should just be baked into plex, but seems they are working on their own sort of setup dealing with ratings and such.

I just hope they do something to break your great work.. Thanks again, I will keep an eye on it..

**Comment by mrjohnpoz** [comment]
Just to follow up - this updated just like you said it would..

**Comment by mynttt** [comment]
Glad to hear it was sorted out!
