### ISSUE TITLE
Warnings in the log

### ISSUE THREAD

**Issue by arsaboo** [mynttt/UpdateTool#36]
I have a lot of these warnings:
```
[WARN ] - 2020-09-03 21:43:24 @ ImdbDatabaseSupport.updateNewAgentMetadataMapping: No external metadata provider id associated with this guid plex://movie/5d776834999c64001ec2f3c6 (MOVIE_NAME). This item will not be processed any further.
```

When I look at the movie in Plex, I can see an IMDB rating. Is there anything that I should do about the warning?

**Comment by mynttt** [comment]
For these mappings to work with the Plex beta it is required to do a full metadata refresh as mentioned [here](https://forums.plex.tv/t/native-plex-agents-allow-access-to-external-provider-ids-for-media-eg-imdb-tmdb-tvdb/619090/130). Otherwise the mapped data does not exist yet and causes these warnings. If you're not using at least beta 1.20.1 UpdateTool won't work with the new movie agent.

Otherwise you can try this query to confirm that the mapping exists or not exists.

```sql
SELECT t.tag FROM taggings tg LEFT JOIN tags t ON tg.tag_id = t.id AND t.tag_type = 314 WHERE tg.metadata_item_id = (SELECT id FROM metadata_items WHERE guid = 'plex://movie/5d776834999c64001ec2f3c6') AND t.tag NOT NULL
```
