### ISSUE TITLE
More a question on xml entries in log vs issue

### ISSUE THREAD

**Issue by mrjohnpoz** [mynttt/UpdateTool#38]
So see these for both movies and shows
[WARN ] - 2020-09-09 21:24:59 @ ImdbPipeline.updateXML: 16 XML file(s) have failed to be updated due to them not being present on the file system.
[WARN ] - 2020-09-09 21:24:59 @ ImdbPipeline.updateXML: This is not an issue as they're not important for Plex as it reads the ratings from the database.

Is there a way to clean these up, or add the missing XMLs?  Clearly most everything has them since the numbers are minor, 16 out of 2500 some movies.. And 154 for tv shows, while there are 13K some episodes and 337 actual shows, etc.

Is there something to I can do to remove said warnings?  Related to that, if not really an issue - why log it at all?

**Comment by mynttt** [comment]
I have no idea what these XML files do tbh. The update is basically just to reflect the database changes as well. I found out that modifying these files does not change anything at all. But because Plex is such a mess it's hard to know what their real purpose is so I don't feel comfortable to remove this part of the tool (even tho I think nothing bad would happen). 

You're right with the errors being annoying tho. I'll add a flag that you can set to suppress all XML related errors.

**Comment by mynttt** [comment]
Disabled by default. If you miss noise in your logs just set the flag `VERBOSE_XML_ERROR_LOG` :^)

**Comment by mrjohnpoz** [comment]
Well that would work too ;)  I will have to do a bit of digging on what they suppose to be there for - why would some not have them?  Its not like I might not have looked at the xml for only 16 movies.. so they never got created.. odd..  Thanks!!!
