### ISSUE TITLE
Only Episodes

### ISSUE THREAD

**Issue by karetarakbas** [mynttt/UpdateTool#59]
Hello,

I have just update my library. Movies worked fine but in my tv library only tv show episodes have been updated not TV shows itself.

Thanks in advance.

**Comment by mynttt** [comment]
I can't investigate this issue unless you send me your Plex database per email.

**Comment by karetarakbas** [comment]
There is a lot db files in Plex Media Server/Plug-in Support/Databases folder. So which one is the right one?

**Comment by mynttt** [comment]
`com.plexapp.plugins.library.db` is the correct one.

**Comment by karetarakbas** [comment]
Sorry for late response what is  your mail adres?

**Comment by mynttt** [comment]
marc@herschel.io

**Comment by nickolasjamesw** [comment]
Same issue for me as well. Emailed you the db file.

**Comment by mynttt** [comment]
@nickolasjamesw Retrieved it! I might look into it after the 24.4 as I'm currently not in my home country.

**Comment by mynttt** [comment]
@karetarakbas @nickolasjamesw I tested it on my system with the DB I recieved and it works fine. My guess is that both of you don't have access to a TVDB API Key (?). A lot of episodes in the DB seem to use the old agent still. Those need access to the TVDB API as else it is not possible to find out the IMDB id for them.

Here are the results of some queries on that database:

```sql
SELECT COUNT(*) FROM metadata_items WHERE library_section_id = 2 AND parent_id IS NULL AND guid LIKE "com.plexapp.agents.thetvdb%";

-- Shows using the old agent
-> 89

SELECT COUNT(*) FROM metadata_items WHERE library_section_id = 2 AND parent_id IS NULL AND guid LIKE "plex://show/%";

-- Shows using the new agent
-> 11

SELECT COUNT(*) FROM metadata_items WHERE library_section_id = 2 AND parent_id IS NOT NULL AND guid LIKE "plex://episode/%";

-- Episodes using the new agent
-> 395

SELECT COUNT(*) FROM metadata_items WHERE library_section_id = 2 AND guid LIKE "%thetvdb://%/%/%"

-- Episodes using the old agent
-> 4514

```

Seasons are not supported by TVDB and thus not relevant here. My guess is that because the TVDB access is missing those can't be processed. Which might look like only episodes are processed as they use the newer agent more often then the shows. I had tons of TVDB requests on my system while testing which supports my theory.

@nickolasjamesw 

This is the amount of changed items in your TV Show library:

![3](https://user-images.githubusercontent.com/22261092/116863919-4b1ef280-ac07-11eb-9000-7ec51af304e4.PNG)

Here are some randomly picked sample shows that now have ratings (I have not compared if they did not have a rating before, if you have a show that is missing a rating let me know and I can look up if it was modified in my testrun): 

![1](https://user-images.githubusercontent.com/22261092/116864021-77d30a00-ac07-11eb-8a08-bfa110ed551a.PNG)

![2](https://user-images.githubusercontent.com/22261092/116864024-7a356400-ac07-11eb-85ab-6d1b5a2a1a59.PNG)

If you have access to a valid TVDB API key let me know because then it would still be a stange issue.

**Comment by karetarakbas** [comment]
Thank you very much. As your guess I dont have tvdb api key. There is no free tvdb api, right?

**Comment by mynttt** [comment]
Sadly they've paywalled their service. The old v3 API keys are still free if you have one (they don't give out new keys anymore) until they shutdown v3. v4 is only accessible by paying.

**Comment by KnifeFed** [comment]
Just so I have this clear, it's impossible to get IMDb ratings for TV shows (not just episodes) unless you have a TVDB API key?
