### ISSUE TITLE
My movies are successfully able to  update But TV shows do Not

### ISSUE THREAD

**Issue by Avyayy** [mynttt/UpdateTool#82]
It shows New TV Show Agent Library with ID: 1 will not be precessed by updateTool . Please register with environment
I am using GUI

**Comment by mynttt** [comment]
This is still an old feature of when the new agent for series was introduced and I wanted users to opt-in instead of using it by default because by then there was still expected volatility from Plex's future development.

It looks like it has matrued now and I should rethink this approach and offer an opt-in all option.

In your case you can solve this by adding the libraries with the IDs that you want in the marked field (multiple values need to be seperated by a `,`).

![grafik](https://user-images.githubusercontent.com/22261092/149840085-17b8b8a6-1482-41a8-af06-cf95b048d8bf.png)
