### ISSUE TITLE
Episodes Updated But not the show as an whole 

### ISSUE THREAD

**Issue by Ackerman69** [mynttt/UpdateTool#85]
Episodes imdb are updated with an imdb badge
But the whole show did not update as an whole still shos tmdb ratings only

**Comment by mynttt** [comment]
This is likely because you have no TVDB API Key supplied. I've had multiple people asking this the last days so I guess something changed in Plex that they stop adding IMDB IDs to the Shows and only to the episodes. I'll copy paste the text I've just added to the readme a few minutes ago here:

> If you get rating updates on your episodes but not on your TV Shows, you'll have to get access to a TVDB API key. This is because the tool finds IMDB IDs that are associated with the episodes in the database, but for the TV Shows only finds TVDB IDs that have to be resolved into IMDB IDs by calling their API. Unless you have a key, this is not possible and means that no updates are processed for these items.

**Comment by Ackerman69** [comment]
I see it wont work with just tmdb api 
Can i manually put it in?

**Comment by mynttt** [comment]
If you have a TMDB API Key at the moment and it still does not update the TV Shows it probably will not work - otherwise just try it out. Do you use docker or the GUI?

In the GUI you can add the key via a textbox - for the docker you'll have to set the correct [environment variable](https://github.com/mynttt/UpdateTool#environment-variables-guide).

TVDB API Keys are behind a paywall nowadays, sadly. https://thetvdb.com/subscribe

**Comment by burkasaurusrex** [comment]
fwiw you can earn a TVDb API pretty quickly (took me a couple hours one evening): https://thetvdb.com/points

**Comment by mynttt** [comment]
@burkasaurusrex Good to know! I'll add it to the important section in case people don't want to pay them. At least they reduced their price from the ridiculous 11$/month to year nowadays.
